POST http://localhost:3000/users
Content-Type: application/json 

{
    "name": "Peter Doe",
    "email": "brayohndwiga@gmail.com",
    "password": "Pass@123"
}


### LOGIN
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "brayohndwiga.com",
    "password": "Pass@123"
}

