POST http://localhost:3000/users/create
Content-Type: application/json

{
    "username": "user2",
    "password": "B@123"
}


### LOGIN
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "user5",
    "password": "E@123"
}

###HELLO
GET http://localhost:3000/
