POST http://localhost:3000/users/create

{
    "username": "jren",
    "password": "Cass@123"
}


### LOGIN
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "Peter Doe",
    "password": "Pass@123"
}

###HELLO
GET http://localhost:3000/
